### ISSUE TITLE
Game crashes on EVA (KSP v1.3.0, TR v2.5.4)

### ISSUE THREAD

**Issue by Cy4nX** [RangeMachine/TextureReplacer#4]
Error:
When I send a Kerbal on EVA, the game crashes.

Steps to Reproduce:
1. Launch a vessel with Kerbals on board
2. Click "EVA" on one of the Kerbals
3. Game crashes

Mods Installed:
TextureReplacer

[KSP log](https://pastebin.com/77QmnfQU)

**Comment by RangeMachine** [comment]
I will update TR for 1.3.0 on the next week.

**Comment by RangeMachine** [comment]
Fixed. Download latest release.
