### ISSUE TITLE
KSP/TR/Visor shader no longer in KSP as of 1.8

### ISSUE THREAD

**Issue by linuxgurugamer** [RangeMachine/TextureReplacer#6]
Generates NullRef errors as a result.

I'm working on a PR for this and some other minor issues related to the new version of Unity

Here is a handy link for a list of all shaders in 1.8:
https://github.com/GER-Space/Kerbal-Konstructs/wiki/Shaders-in-1.8

**Comment by RangeMachine** [comment]
Merged pull request.
